
# ACS 1 Fetch Start Year
acs_start_year: 2012

# ACS 1 Variable Names to Fetch
variables_to_fetch : [
                      "NAME", 
                      "B01003_001E", 
                      "B05002_003E",
                      "B07001_065E",
                      "B04006_049E",
                      "B04007_002E",
                      "B19013_001E",
                      "B25064_001E",
                     # "B25088_001E",
                     # "B25070_001E",
                      "B25077_001E",
                      "B25058_001E",
                      "B25105_001E",
                      "B25119_001E",
                      "B25119_002E",
                      "B25119_003E",
                      ]