
# ACS 1 Fetch Start Year
acs_start_year: 2012

# ACS 1 Variable Names to Fetch
variables_to_fetch : [
                      "NAME", 
                      "B01003_001E", 
                      "B05002_003E",
                      "B07001_065E",
                      "B04006_049E",
                      "B04007_002E",
                      "B19013_001E",
                      "B25064_001E",
                      'B19001_001E',
                      'B19001_002E',
                      'B19001_003E',
                      'B19001_004E',
                      'B19001_005E',
                      'B19001_006E',
                      'B19001_007E',
                      'B19001_008E',
                      'B19001_009E',
                      'B19001_010E',
                      'B19001_011E',
                      'B19001_012E',
                      'B19001_013E',
                      'B19001_014E',
                      'B19001_015E',
                      'B19001_016E',
                      'B19001_017E',
                      "B25077_001E",
                      "B25058_001E",
                      "B25105_001E",
                      "B25119_001E",
                      "B25119_002E",
                      "B25119_003E",
                      ]